apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kubernetes\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: datadogloggingdemo
  name: datadogloggingdemo
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
    - name: "8443"
      port: 8443
      targetPort: 443
  selector:
    io.kompose.service: datadogloggingdemo
status:
  loadBalancer: {}
