FROM gcr.io/datadoghq/agent:latest AS base
#COPY ["DatadogAgent/etc/datadog-agent/datadog.yaml", "etc/datadog-agent/datadog.yaml"]
#RUN mkdir -p etc/datadog-agent/conf.d/datadogtestapi.d
#COPY ["DatadogAgent/etc/datadog-agent/conf.d/datadogtestapi.d/conf.yaml", "etc/datadog-agent/conf.d/datadogtestapi.d/conf.yaml"]
# This doesn't dp amything ??
#LABEL "com.datadoghq.ad.logs"='[{"source": "datadogtestapi_datadogtestapi", "service": "service-api-dc"}]'
